name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile cv_it.tex
        uses: dante-ev/latex-action@master
        with:
          root_file: cv_it.tex
      - name: Compile cv_en.tex
        uses: dante-ev/latex-action@master
        with:
          root_file: cv_en.tex
